### ISSUE TITLE
ivlsu missing data within model region

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVM#15]
tests show no data at point  -115.5000    32.700 which should be within the model region. Check why no properties are defined at this point.

**Comment by meihuisu** [comment]
ivlsu model is a basin model. Not all locations within model region boundary returns  material property in a basin model.
![Screen Shot 2022-07-01 at 10 47 30 AM](https://user-images.githubusercontent.com/9042455/176945551-408dcd55-0a6a-4605-aa79-6f14959506a7.png)

**Comment by meihuisu** [comment]
![Screen Shot 2022-07-01 at 10 56 13 AM](https://user-images.githubusercontent.com/9042455/176946530-df7e3f4c-1e6d-4972-a5e6-8c1a548cb2c2.png)
