### ISSUE TITLE
modular basins. San Gabriel basin

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#17]
Here is a zip archive with the data voxet and test points for the San Gabriel basin.
[CVMHB-San-Gabriel-Basin.zip](https://github.com/SCECcode/ucvm/files/8334852/CVMHB-San-Gabriel-Basin.zip)

![image](https://user-images.githubusercontent.com/6171115/159750140-88402d47-7fcc-4aa0-88c7-0a0c4827ef24.png)

**Comment by andreasplesch** [comment]
A few technical notes to help prepare additional basin models:

- Extract empty grid from large CVMH grid, using extent of basin points
- populate/paint with basin data points, rename properties
- generate new voxet grid from box (_fromBox grid) of this grid, using the same number of cells in each dimension
- populate/paint new grid with first grid cell properties
- generate points from grid preserving all properties
- save grid as Gocad ASCII, export points as ASCII

possible improvement:

- Extract empty grid from large CVMH grid, using extent of basin points
- generate new voxet grid from box (_fromBox grid) of this grid, using the same number of cells in each dimension
- populate/paint with basin data points, rename properties
...

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
