### ISSUE TITLE
modular basins: Ventura basin

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#20]
Here is a zip archive with the voxet data and test points for the Ventura basin:
[CVMHB-Ventura-Basin.zip](https://github.com/SCECcode/ucvm/files/8491731/CVMHB-Ventura-Basin.zip)

**Comment by andreasplesch** [comment]
![image](https://user-images.githubusercontent.com/6171115/163462694-856550a7-1dd9-4b70-973d-8d32c97c8a3a.png)

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
