### ISSUE TITLE
modular basins: Inner Borderland

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#28]
Zip archive is attached below.
[CVMHB-Inner-Borderland-Basin.zip](https://github.com/SCECcode/ucvm/files/8734231/CVMHB-Inner-Borderland-Basin.zip)

Generation:

1. extract empty voxet from CVMH
2. create new voxet from this empty voxet's box using the same number of cell in U,V,W (for reindexing)
3. paint with basin points properties
4. rename properties with suffix

5. Generate voxet format

![image](https://user-images.githubusercontent.com/6171115/169402868-32742f9d-f562-435d-b390-96329c1f8fcd.png)

**Comment by andreasplesch** [comment]
points: 103MB too large ?

**Comment by andreasplesch** [comment]
points: 
7zip archive [CVMHB-Inner-Borderland-Basin-points-7zip.zip](https://github.com/SCECcode/ucvm/files/8800755/CVMHB-Inner-Borderland-Basin-points-7zip.zip)
or zip with bzip2 compression: 
[CVMHB-Inner-Borderland-Basin-points-bzip2.zip](https://github.com/SCECcode/ucvm/files/8800822/CVMHB-Inner-Borderland-Basin-points-bzip2.zip)

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
