### ISSUE TITLE
modular basins: Ridge Basin

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#29]
voxet data: 
[CVMHB-Ridge-Basin.zip](https://github.com/SCECcode/ucvm/files/8734290/CVMHB-Ridge-Basin.zip)

![image](https://user-images.githubusercontent.com/6171115/169406340-b7dadc13-6790-45f5-83b9-6170cae46ad8.png)

**Comment by andreasplesch** [comment]
points: 
[~CVMHB-Ridge-Basin-points.zip~](https://github.com/SCECcode/ucvm/files/8800713/CVMHB-Ridge-Basin-points.obsolete.zip)

**Comment by andreasplesch** [comment]
updated points: 
[CVMHB-Ridge-Basin-points.zip](https://github.com/SCECcode/ucvm/files/8827761/CVMHB-Ridge-Basin-points.zip)

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
