### ISSUE TITLE
modular basins: Salton Trough

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#30]
Basin may have one extra cell at base, only in southeastern quadrant. fixed

basin data:
[CVMHB-Salton-Trough-Basin.zip](https://github.com/SCECcode/ucvm/files/8744166/CVMHB-Salton-Trough-Basin.zip)

![image](https://user-images.githubusercontent.com/6171115/169612103-a9028064-144b-4f52-bf4e-7647ff2c6b5f.png)

**Comment by andreasplesch** [comment]
points: 51MB too large ?

**Comment by andreasplesch** [comment]
split with:
```$ split -d -b 24M --additional-suffix=.zip CVMHB-Salton-Trough-Basin-points-bzip2.zip CVMHB-Salton-Trough-Basin-points-bzip2-zip. ```
[CVMHB-Salton-Trough-Basin-points-bzip2-zip.01.zip](https://github.com/SCECcode/ucvm/files/8800791/CVMHB-Salton-Trough-Basin-points-bzip2-zip.01.zip)
[CVMHB-Salton-Trough-Basin-points-bzip2-zip.00.zip](https://github.com/SCECcode/ucvm/files/8800792/CVMHB-Salton-Trough-Basin-points-bzip2-zip.00.zip)
recombine with:
```$ cat CVMHB-Salton*zip >  CVMHB-Salton-Trough-Basin-points.zip```

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
