### ISSUE TITLE
modular basins: San Bernardino

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#31]
voxet data: 
[CVMHB-San-Bernardino-Basin.zip](https://github.com/SCECcode/ucvm/files/8743406/CVMHB-San-Bernardino-Basin.zip)

![image](https://user-images.githubusercontent.com/6171115/169581001-a19fedca-cbd8-4656-b3b2-a421dcff0bac.png)

**Comment by andreasplesch** [comment]
points: 
[CVMHB-San-Bernardino-Basin-points.zip](https://github.com/SCECcode/ucvm/files/8800707/CVMHB-San-Bernardino-Basin-points.zip)

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
