### ISSUE TITLE
modular basins: Santa Barbara Channel

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#32]
basin data: 
[CVMHB-Santa-Barbara-Channel-Basin.zip](https://github.com/SCECcode/ucvm/files/8743541/CVMHB-Santa-Barbara-Channel-Basin.zip)

![image](https://user-images.githubusercontent.com/6171115/169596893-71ab8a63-22c1-461e-bca4-4aac9046ed2e.png)

**Comment by andreasplesch** [comment]
points: 
[CVMHB-Santa-Barbara-Channel-Basin-points.zip](https://github.com/SCECcode/ucvm/files/8800697/CVMHB-Santa-Barbara-Channel-Basin-points.zip)

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
