### ISSUE TITLE
modular basins: Santa Maria

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/UCVM#33]
basin data: 
[CVMHB-Santa-Maria-Basin.zip](https://github.com/SCECcode/ucvm/files/8743634/CVMHB-Santa-Maria-Basin.zip)

![image](https://user-images.githubusercontent.com/6171115/169599676-712a461b-edf2-4678-8ddb-dab30821c37c.png)

**Comment by andreasplesch** [comment]
points: 
[CVMHB-Santa-Maria-Basin-points.zip](https://github.com/SCECcode/ucvm/files/8800695/CVMHB-Santa-Maria-Basin-points.zip)

**Comment by meihuisu** [comment]
https://github.com/SCECcode/cvmhbn
