### ISSUE TITLE
CARC spack libraries

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVM#37]
On USC CARC, an export LD_PRELOAD=/spack/apps/gcc/8.3.0/lib64/libstdc++.so.6 command is needed in users .bashrc. I believe this is based on a mis-configuraiton of the the CARC system. We should document when this is needed.

**Comment by meihuisu** [comment]
This is only a problem with gcc on USC CARC system when using 8.3.0. This would not be needed on other system or (maybe) when gcc is upgraded at CARC.
