### ISSUE TITLE
Detect MPI libraries

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVM#38]
on SDSC Expanse, with the simple module list, the MPI libraries don't build. Determine which modules need to be added to Expanse to build the UCVM mpi libraries.

**Comment by meihuisu** [comment]
on SDSC Expanse, 
following setup is tested to work with UCVM 22.7's   mpi-enabled 
example acceptance tests
---------------------------------------------------

module load  gcc/10.2.0
module load openmpi/4.0.4

unset CC
export UCVM_SALLOC_ENV="--partition=debug  --account=ddp408 --mem=16G"
