### ISSUE TITLE
UCVM version in install script

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVM#5]
20 0.307 All Flag: True
#20 0.307 dynamic Flag: True
#20 0.307 
#20 0.307 UCVM 21.7.0 Installation
#20 0.307 Copyright (C) 2021 SCEC. All rights reserved.
#20 0.307 Using local setup.list and system.list ....
#20 0.307 Now check system specific conditions.

Also, the copyright is by USC rather than SCEC

**Comment by meihuisu** [comment]
Updated in ucvm_setup.py
