### ISSUE TITLE
ucvm install version number incorrect

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVM#8]
> [15/24] RUN ./ucvm_setup.py -a -d < setup_inputs.txt:
#19 0.301 All Flag: True
#19 0.301 dynamic Flag: True
#19 0.301 
#19 0.301 UCVM 21.7.0 Installation
#19 0.301 Copyright (C) 2021 SCEC. All rights reserved.
#19 0.301 Using local setup.list and system.list ....
#19 0.301 Now check system specific conditions.
#19 0.301 System_data - k:  h2ologin
#19 0.301 System_data - k:  all
#19 0.301 Using local setup.list file

 UCVM 21.7.0 Installation is incorrect.

**Comment by meihuisu** [comment]
bumped it to 21.10.0 in GitHub
